### ISSUE TITLE
Refused to load the font 'data:font/woff;base64

### ISSUE THREAD

**Issue by LANole** [BlackrockDigital/startbootstrap-modern-business#22]
Downloaded and fired up a simple NodeJS server... the sites index page is comes right up. When I try to go to any other page I get this CSP error. I've tried setting the CSP various ways but nothing is working. Any ideas? Anyone run into this before? Many thanks!

PS...love the template.

**Comment by LANole** [comment]
I'm an idiot... had some middleware in the wrong order.

**Comment by chinu13Jain** [comment]
can you please explain the issue??i am facing same problem
