### ISSUE TITLE
Cannot get carousel to activate

### ISSUE THREAD

**Issue by TechUserTech** [BlackrockDigital/startbootstrap-modern-business#6]
Hello, 
I am very new to Bootstrap, HTML, CSS and JS.

I downloaded this theme which is wonderful on the website but the actually downloaded html pages do not accurately reflect the preview pages-maybe this is normal but it is not what I have experienced in other themes I have downloaded but like I mentioned, I am new to all of this. It is easier for me to start out with a template and comment out or change certain parts to see how the page reacts. 

The home/index page is incredible although the download I have looks nothing like the preview including the menu which I cannot get to collapse or toggle even though I did not change anything but that is separate issue. What I was most interested in with this theme was the carousel but I cannot get the carousel to activate. I have tried various web searches and have copied the html exactly and checked the JS but still I cannot get the carousel. Even with the theme, the only thing I edited was the actual placeholder image but still not working. What I can get are full width images on the screen and that is it-no carousel. There is something I am obviously missing but I do not know what it is so any help/guidance provided would be appreciated. 

Thank you for your time.

**Comment by davidtmiller** [comment]
Check the docs at http://getbootstrap.com to see how to get the slider to activate. The slider should be activating within the theme, but if you changed some classes names, ID's, or removed some scripts this might have been removed.
