### ISSUE TITLE
Cannot get contact form to work

### ISSUE THREAD

**Issue by elcy-b** [BlackrockDigital/startbootstrap-modern-business#63]
Unable to get the contact form to work. When I checked the contact_me.js it looks like `$this` is undefined in three instances. 
22   `$this = $('#sendMessageButton');`
23      `$this.prop('disabled', true); `
70            ` $this.prop('disabled', false);` // Re-enable submit button when AJAX call is complete

and that the    `submitError: function` is defined but not used.
I am not versed in JS so I am just guessing that maybe this is part of the issue.  I haven't seen a contact form that did not have form action specified in the html so I am uncertain how this form is supposed to work. Thanks for any help.

**Comment by zeufparis** [comment]
I have just download the zip, unzip it, run it through my Wampserver and Smpt4dev.
Everything works just fine right away... Did you modify the **contact_me.js** file ?
The form datas are sent with Ajax method in the JS (JS grabs the datas and send them via AJAX method. Action and Method are in the JS : `url: "././mail/contact_me.php"`, `type: "POST"`)
`$this` is the name of the submit button's div jQuery style.

**Comment by elcy-b** [comment]
Thanks for checking and explaining. I found that it works as long as I don't use the email address with the domain name.  I can use a gmail address and it sends.  Super.
