### ISSUE TITLE
Change slide picture

### ISSUE THREAD

**Issue by moi88** [BlackrockDigital/startbootstrap-modern-business#7]
Hello and great job already.
I want to know how to change the slide lines for my pictures to me?
In this line for example:
 <code><div class = "fill" style = "background-image: url ('http://placehold.it/1900x1080&text=Slide Two');"> </ div></code>
I tried to change with <div class = "fill" style = "background-image: url ('house.jpg Two');"> </ div> which is the root of my site, but it does m 'not display my house photo. thanks for your help

**Comment by moi88** [comment]
<div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
by  <div class="fill" style="background-image:url('slide1.jpg Two');"></div>
 can you help me

**Comment by davidtmiller** [comment]
You can see the slider image paths directly in the HTML. Just change the image paths in the HTML where the slider code is located and you should be all set!
