### ISSUE TITLE
Slider text cut off on mobile

### ISSUE THREAD

**Issue by beakernx01** [BlackrockDigital/startbootstrap-modern-business#8]
I love this template! Thank you! 

That said, having a small problem. The text captions on the slider are getting cut off on my iPhone 5s (portrait or landscape, in Safari and Chrome) and in landscape on a 7" Kindle Fire. 

On the desktop, when I shrink the browser's width, only the longest quotes get cut on the top, but on the iPhone 5s, 75% of the slider image itself, along with the text, is not visible in landscape. I get 4 lines of text in Portrait but can only see the slider indicators in Landscape.

Note, I did increase the size of the header to accommodate the logo.
.navbar-brand{float:left;height:50px;padding:5px 5px;font-size:18px;line-height:20px}

But I don't think that accounts for all the missing text.  

Screen caps from iPhone5s: 

![2016-02-24 12 22 52](https://cloud.githubusercontent.com/assets/1695793/13300005/d06800f8-daf2-11e5-99ea-c4ffb0ad733e.png)
![2016-02-24 12 22 43](https://cloud.githubusercontent.com/assets/1695793/13300006/d07f5064-daf2-11e5-8adb-c03015151275.png)

Any suggestions?

Thanks,

Tom

**Comment by davidtmiller** [comment]
Work with the text sizing of the content and the positioning of the caption content until you get your desired effect.

**Comment by beakernx01** [comment]
I actually figured it out a while ago. Great template. Thanks!
_______________________________
