### ISSUE TITLE
Hiding the sidebar on mobile

### ISSUE THREAD

**Issue by beakernx01** [BlackrockDigital/startbootstrap-modern-business#9]
Hi there, Is there a way to hide the sidebar on the mobile view? I've got a long one, and UX-wise, I'd rather the view just see the page headline when changing pages and not the sidebar again. They may not even realize they're on a different page.

I tried the .hidden-sm and .hidden-xs to no affect, but then again, I'm new to bootstrap and might be implementing it wrong.

http://www.edisoncg.com/edisonmfs

Any suggestions?

Thanks,

Tom

**Comment by davidtmiller** [comment]
Adding the .hidden-xs and .hidden-sm classes should do the trick. Just make sure you're adding the classes in the right spots.
